# 공공 데이터 불러오기 - 경기도 성남시 인구 및 세대 현황 20250131

In [101]:
import pandas as pd

data = pd.read_csv('population.csv', encoding = 'euc-kr')
data.head()

,구별,동,인구수_계,인구수_남,인구수_여,19세 이상_계,19세 이상_남,19세 이상_여,65세 이상_계,65세 이상_남자,65세 이상_여자,세대수,재외국민,데이터기준일자
0,수정구,신흥1동,12278,6558,5720,11490,6145,5345,2934,1279,1655,7587,17,2025-01-31
1,수정구,신흥2동,31480,15265,16215,26514,12784,13730,4840,2222,2618,12269,42,2025-01-31
2,수정구,신흥3동,10762,5757,5005,10035,5387,4648,2458,1133,1325,6457,9,2025-01-31
3,수정구,태평1동,13872,7195,6677,13061,6786,6275,3413,1510,1903,8332,21,2025-01-31
4,수정구,태평2동,13978,7064,6914,12821,6485,6336,3215,1377,1838,7645,18,2025-01-31

# Series

In [37]:
example = data['구별']
example

0     수정구
1     수정구
2     수정구
3     수정구
4     수정구
5     수정구
6     수정구
7     수정구
8     수정구
9     수정구
10    수정구
11    수정구
12    수정구
13    수정구
14    수정구
15    수정구
16    수정구
17    중원구
18    중원구
19    중원구
20    중원구
21    중원구
22    중원구
23    중원구
24    중원구
25    중원구
26    중원구
27    중원구
28    분당구
29    분당구
30    분당구
31    분당구
32    분당구
33    분당구
34    분당구
35    분당구
36    분당구
37    분당구
38    분당구
39    분당구
40    분당구
41    분당구
42    분당구
43    분당구
44    분당구
45    분당구
46    분당구
47    분당구
48    분당구
49    분당구
Name: 구별, dtype: object

In [39]:
example[3]

'수정구'

In [41]:
example.values

array(['수정구', '수정구', '수정구', '수정구', '수정구', '수정구', '수정구', '수정구', '수정구',
       '수정구', '수정구', '수정구', '수정구', '수정구', '수정구', '수정구', '수정구', '중원구',
       '중원구', '중원구', '중원구', '중원구', '중원구', '중원구', '중원구', '중원구', '중원구',
       '중원구', '분당구', '분당구', '분당구', '분당구', '분당구', '분당구', '분당구', '분당구',
       '분당구', '분당구', '분당구', '분당구', '분당구', '분당구', '분당구', '분당구', '분당구',
       '분당구', '분당구', '분당구', '분당구', '분당구'], dtype=object)

In [43]:
example.index

RangeIndex(start=0, stop=50, step=1)

# DataFrame

In [27]:
df = pd.DataFrame(data, columns = ['구별', '동', '세대수', '재외국민'])
df

     구별              동    세대수  재외국민
0   수정구  신흥1동            7587    17
1   수정구  신흥2동           12269    42
2   수정구  신흥3동            6457     9
3   수정구  태평1동            8332    21
4   수정구  태평2동            7645    18
5   수정구  태평3동            6511    17
6   수정구  태평4동            6024    12
7   수정구  수진1동            6781    12
8   수정구  수진2동            7520    33
9   수정구  단대동             6503    22
10  수정구  산성동             2168    25
11  수정구  양지동             4245     6
12  수정구  복정동             6562    18
13  수정구  위례동            18842   119
14  수정구  신촌동             2008    13
15  수정구  고등동             5259    28
16  수정구  시흥동             2058    17
17  중원구  성남동            18506    50
18  중원구  중앙동             7580    18
19  중원구  금광1동            8225    16
20  중원구  금광2동           12153    42
21  중원구  은행1동            4387     7
22  중원구  은행2동           10791    48
23  중원구   상대원1동         12139    23
24  중원구   상대원2동          1607    10
25  중원구   상대원3동          6320    14
26  중원구   하대원동           8075    34
27  중원구  도촌동            10768    50
28  분당구  분당동            10058    89
29  분당구  수내1동            7848   129
30  분당구  수내2동            3204    40
31  분당구  수내3동            5125    29
32  분당구  정자동             6300    61
33  분당구  정자1동           13976   277
34  분당구  정자2동            7274    60
35  분당구  정자3동            6612    71
36  분당구  서현1동           12668   168
37  분당구  서현2동            6555    61
38  분당구  이매1동            9051    90
39  분당구  이매2동            4415    57
40  분당구  야탑1동            7545    60
41  분당구  야탑2동            6005    81
42  분당구  야탑3동           12512    60
43  분당구            금곡동  12014   162
44  분당구            구미동  12530   158
45  분당구           구미1동   7013    88
46  분당구  판교동             9021    96
47  분당구  삼평동             9099    57
48  분당구  백현동            10470    91
49  분당구  운중동            13564   172

In [33]:
df.동

0     신흥1동
1     신흥2동
2     신흥3동
3     태평1동
4     태평2동
5     태평3동
6     태평4동
7     수진1동
8     수진2동
9     단대동
10    산성동
11    양지동
12    복정동
13    위례동
14    신촌동
15    고등동
16    시흥동
17    성남동
18    중앙동
19    금광1동
20    금광2동
21    은행1동
22    은행2동
23     상대원1동
24     상대원2동
25     상대원3동
26     하대원동
27    도촌동
28    분당동
29    수내1동
30    수내2동
31    수내3동
32    정자동
33    정자1동
34    정자2동
35    정자3동
36    서현1동
37    서현2동
38    이매1동
39    이매2동
40    야탑1동
41    야탑2동
42    야탑3동
43              금곡동
44              구미동
45             구미1동
46    판교동
47    삼평동
48    백현동
49    운중동
Name: 동, dtype: object

In [35]:
df.loc[0]

구별                수정구
동       신흥1동
세대수              7587
재외국민               17
Name: 0, dtype: object

In [45]:
df.iloc[3]

구별                수정구
동       태평1동
세대수              8332
재외국민               21
Name: 3, dtype: object

In [49]:
df['debt'] = df['재외국민'] > 80
df

     구별              동    세대수  재외국민   debt
0   수정구  신흥1동            7587    17  False
1   수정구  신흥2동           12269    42  False
2   수정구  신흥3동            6457     9  False
3   수정구  태평1동            8332    21  False
4   수정구  태평2동            7645    18  False
5   수정구  태평3동            6511    17  False
6   수정구  태평4동            6024    12  False
7   수정구  수진1동            6781    12  False
8   수정구  수진2동            7520    33  False
9   수정구  단대동             6503    22  False
10  수정구  산성동             2168    25  False
11  수정구  양지동             4245     6  False
12  수정구  복정동             6562    18  False
13  수정구  위례동            18842   119   True
14  수정구  신촌동             2008    13  False
15  수정구  고등동             5259    28  False
16  수정구  시흥동             2058    17  False
17  중원구  성남동            18506    50  False
18  중원구  중앙동             7580    18  False
19  중원구  금광1동            8225    16  False
20  중원구  금광2동           12153    42  False
21  중원구  은행1동            4387     7  False
22  중원구  은행2동           10791    48  False
23  중원구   상대원1동         12139    23  False
24  중원구   상대원2동          1607    10  False
25  중원구   상대원3동          6320    14  False
26  중원구   하대원동           8075    34  False
27  중원구  도촌동            10768    50  False
28  분당구  분당동            10058    89   True
29  분당구  수내1동            7848   129   True
30  분당구  수내2동            3204    40  False
31  분당구  수내3동            5125    29  False
32  분당구  정자동             6300    61  False
33  분당구  정자1동           13976   277   True
34  분당구  정자2동            7274    60  False
35  분당구  정자3동            6612    71  False
36  분당구  서현1동           12668   168   True
37  분당구  서현2동            6555    61  False
38  분당구  이매1동            9051    90   True
39  분당구  이매2동            4415    57  False
40  분당구  야탑1동            7545    60  False
41  분당구  야탑2동            6005    81   True
42  분당구  야탑3동           12512    60  False
43  분당구            금곡동  12014   162   True
44  분당구            구미동  12530   158   True
45  분당구           구미1동   7013    88   True
46  분당구  판교동             9021    96   True
47  분당구  삼평동             9099    57  False
48  분당구  백현동            10470    91   True
49  분당구  운중동            13564   172   True

In [51]:
del df['debt']
df

     구별              동    세대수  재외국민
0   수정구  신흥1동            7587    17
1   수정구  신흥2동           12269    42
2   수정구  신흥3동            6457     9
3   수정구  태평1동            8332    21
4   수정구  태평2동            7645    18
5   수정구  태평3동            6511    17
6   수정구  태평4동            6024    12
7   수정구  수진1동            6781    12
8   수정구  수진2동            7520    33
9   수정구  단대동             6503    22
10  수정구  산성동             2168    25
11  수정구  양지동             4245     6
12  수정구  복정동             6562    18
13  수정구  위례동            18842   119
14  수정구  신촌동             2008    13
15  수정구  고등동             5259    28
16  수정구  시흥동             2058    17
17  중원구  성남동            18506    50
18  중원구  중앙동             7580    18
19  중원구  금광1동            8225    16
20  중원구  금광2동           12153    42
21  중원구  은행1동            4387     7
22  중원구  은행2동           10791    48
23  중원구   상대원1동         12139    23
24  중원구   상대원2동          1607    10
25  중원구   상대원3동          6320    14
26  중원구   하대원동           8075    34
27  중원구  도촌동            10768    50
28  분당구  분당동            10058    89
29  분당구  수내1동            7848   129
30  분당구  수내2동            3204    40
31  분당구  수내3동            5125    29
32  분당구  정자동             6300    61
33  분당구  정자1동           13976   277
34  분당구  정자2동            7274    60
35  분당구  정자3동            6612    71
36  분당구  서현1동           12668   168
37  분당구  서현2동            6555    61
38  분당구  이매1동            9051    90
39  분당구  이매2동            4415    57
40  분당구  야탑1동            7545    60
41  분당구  야탑2동            6005    81
42  분당구  야탑3동           12512    60
43  분당구            금곡동  12014   162
44  분당구            구미동  12530   158
45  분당구           구미1동   7013    88
46  분당구  판교동             9021    96
47  분당구  삼평동             9099    57
48  분당구  백현동            10470    91
49  분당구  운중동            13564   172

# Case Study

In [53]:
data.shape

(50, 14)

In [55]:
data.head(4)

,구별,동,인구수_계,인구수_남,인구수_여,19세 이상_계,19세 이상_남,19세 이상_여,65세 이상_계,65세 이상_남자,65세 이상_여자,세대수,재외국민,데이터기준일자
0,수정구,신흥1동,12278,6558,5720,11490,6145,5345,2934,1279,1655,7587,17,2025-01-31
1,수정구,신흥2동,31480,15265,16215,26514,12784,13730,4840,2222,2618,12269,42,2025-01-31
2,수정구,신흥3동,10762,5757,5005,10035,5387,4648,2458,1133,1325,6457,9,2025-01-31
3,수정구,태평1동,13872,7195,6677,13061,6786,6275,3413,1510,1903,8332,21,2025-01-31

In [57]:
data.tail(5)

,구별,동,인구수_계,인구수_남,인구수_여,19세 이상_계,19세 이상_남,19세 이상_여,65세 이상_계,65세 이상_남자,65세 이상_여자,세대수,재외국민,데이터기준일자
45,분당구,구미1동,16178,7795,8383,13949,6670,7279,2687,1223,1464,7013,88,2025-01-31
46,분당구,판교동,26558,13036,13522,20372,9842,10530,2954,1419,1535,9021,96,2025-01-31
47,분당구,삼평동,23773,11534,12239,19174,9210,9964,3013,1359,1654,9099,57,2025-01-31
48,분당구,백현동,26416,12656,13760,22011,10373,11638,3879,1746,2133,10470,91,2025-01-31
49,분당구,운중동,37217,18185,19032,29477,14207,15270,4222,2052,2170,13564,172,2025-01-31

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   구별         50 non-null     object
 1   동          50 non-null     object
 2   인구수_계      50 non-null     int64
 3   인구수_남      50 non-null     int64
 4   인구수_여      50 non-null     int64
 5   19세 이상_계   50 non-null     int64
 6   19세 이상_남   50 non-null     int64
 7   19세 이상_여   50 non-null     int64
 8   65세 이상_계   50 non-null     int64
 9   65세 이상_남자  50 non-null     int64
 10  65세 이상_여자  50 non-null     int64
 11  세대수        50 non-null     int64
 12  재외국민       50 non-null     int64
 13  데이터기준일자    50 non-null     object
dtypes: int64(11), object(3)
memory usage: 5.6+ KB

In [61]:
data['세대수'].unique

<bound method Series.unique of 0      7587
1     12269
2      6457
3      8332
4      7645
5      6511
6      6024
7      6781
8      7520
9      6503
10     2168
11     4245
12     6562
13    18842
14     2008
15     5259
16     2058
17    18506
18     7580
19     8225
20    12153
21     4387
22    10791
23    12139
24     1607
25     6320
26     8075
27    10768
28    10058
29     7848
30     3204
31     5125
32     6300
33    13976
34     7274
35     6612
36    12668
37     6555
38     9051
39     4415
40     7545
41     6005
42    12512
43    12014
44    12530
45     7013
46     9021
47     9099
48    10470
49    13564
Name: 세대수, dtype: int64>

In [63]:
data['세대수'].value_counts

<bound method IndexOpsMixin.value_counts of 0      7587
1     12269
2      6457
3      8332
4      7645
5      6511
6      6024
7      6781
8      7520
9      6503
10     2168
11     4245
12     6562
13    18842
14     2008
15     5259
16     2058
17    18506
18     7580
19     8225
20    12153
21     4387
22    10791
23    12139
24     1607
25     6320
26     8075
27    10768
28    10058
29     7848
30     3204
31     5125
32     6300
33    13976
34     7274
35     6612
36    12668
37     6555
38     9051
39     4415
40     7545
41     6005
42    12512
43    12014
44    12530
45     7013
46     9021
47     9099
48    10470
49    13564
Name: 세대수, dtype: int64>

In [67]:
data['재외국민'].sum()

2898

In [69]:
data['재외국민'].max()

277

In [71]:
data['재외국민'].min()

6

In [73]:
data['재외국민'].idxmax()

33

In [75]:
idx_max = data['재외국민'].idxmax()
data['동'].iloc[idx_max]

'정자1동         '

In [77]:
data['재외국민'].idxmin()

11

In [79]:
idx_min = data['재외국민'].idxmin()
data['동'].iloc[idx_min]

'양지동          '

In [81]:
data['재외국민'].mean()

57.96

In [83]:
data['재외국민'].median()

42.0

In [85]:
data['재외국민'].var()

3011.7942857142866

In [87]:
data['재외국민'].std()

54.87981674271778

# 수정구 재외국민의 평균, 분산, 중앙값을 구하라

In [89]:
print(data.iloc[0:17]['재외국민'].mean())
print(data.iloc[0:17]['재외국민'].var())
print(data.iloc[0:17]['재외국민'].median())

25.235294117647058
663.1911764705882
18.0

In [97]:
# Column 산술 연산을 통해 19세 이상 인구수 구하기
data['19세 이상 인구수'] = data['19세 이상_남'] + data['19세 이상_여']
data

,구별,동,인구수_계,인구수_남,인구수_여,19세 이상_계,19세 이상_남,19세 이상_여,65세 이상_계,65세 이상_남자,65세 이상_여자,세대수,재외국민,데이터기준일자,19세 이상 인구수,19세 이상 남녀 차이,재외국민/세대수
0,수정구,신흥1동,12278,6558,5720,11490,6145,5345,2934,1279,1655,7587,17,2025-01-31,11490,800,0.002241
1,수정구,신흥2동,31480,15265,16215,26514,12784,13730,4840,2222,2618,12269,42,2025-01-31,26514,-946,0.003423
2,수정구,신흥3동,10762,5757,5005,10035,5387,4648,2458,1133,1325,6457,9,2025-01-31,10035,739,0.001394
3,수정구,태평1동,13872,7195,6677,13061,6786,6275,3413,1510,1903,8332,21,2025-01-31,13061,511,0.002520
4,수정구,태평2동,13978,7064,6914,12821,6485,6336,3215,1377,1838,7645,18,2025-01-31,12821,149,0.002354
5,수정구,태평3동,11968,6153,5815,10996,5665,5331,2915,1311,1604,6511,17,2025-01-31,10996,334,0.002611
6,수정구,태평4동,11213,5782,5431,10168,5234,4934,2517,1120,1397,6024,12,2025-01-31,10168,300,0.001992
7,수정구,수진1동,11091,5875,5216,10464,5550,4914,3061,1363,1698,6781,12,2025-01-31,10464,636,0.001770
8,수정구,수진2동,14565,7357,7208,13379,6749,6630,3763,1706,2057,7520,33,2025-01-31,13379,119,0.004388
9,수정구,단대동,14349,7059,7290,12673,6176,6497,3091,1320,1771,6503,22,2025-01-31,12673,-321,0.003383
10,수정구,산성동,4543,2276,2267,4037,2005,2032,1093,471,622,2168,25,2025-01-31,4037,-27,0.011531
11,수정구,양지동,9050,4463,4587,8120,3985,4135,2060,900,1160,4245,6,2025-01-31,8120,-150,0.001413
12,수정구,복정동,10156,5735,4421,9431,5367,4064,1277,613,664,6562,18,2025-01-31,9431,1303,0.002743
13,수정구,위례동,45783,22143,23640,37007,17768,19239,6716,3115,3601,18842,119,2025-01-31,37007,-1471,0.006316
14,수정구,신촌동,4498,2379,2119,3677,1969,1708,571,269,302,2008,13,2025-01-31,3677,261,0.006474
15,수정구,고등동,11716,5735,5981,9822,4794,5028,1704,775,929,5259,28,2025-01-31,9822,-234,0.005324
16,수정구,시흥동,3419,1816,1603,3180,1690,1490,693,335,358,2058,17,2025-01-31,3180,200,0.008260
17,중원구,성남동,32221,16854,15367,29747,15615,14132,6769,3096,3673,18506,50,2025-01-31,29747,1483,0.002702
18,중원구,중앙동,16733,8516,8217,14295,7272,7023,3103,1409,1694,7580,18,2025-01-31,14295,249,0.002375
19,중원구,금광1동,19571,9592,9979,16276,7956,8320,2689,1220,1469,8225,16,2025-01-31,16276,-364,0.001945
20,중원구,금광2동,24116,11918,12198,21742,10724,11018,5184,2322,2862,12153,42,2025-01-31,21742,-294,0.003456
21,중원구,은행1동,9390,4641,4749,8332,4079,4253,1811,794,1017,4387,7,2025-01-31,8332,-174,0.001596
22,중원구,은행2동,21405,10557,10848,19530,9590,9940,5068,2167,2901,10791,48,2025-01-31,19530,-350,0.004448
23,중원구,상대원1동,23730,12374,11356,21365,11166,10199,5141,2343,2798,12139,23,2025-01-31,21365,967,0.001895
24,중원구,상대원2동,3042,1602,1440,2776,1457,1319,698,339,359,1607,10,2025-01-31,2776,138,0.006223
25,중원구,상대원3동,11311,5934,5377,10385,5465,4920,2816,1322,1494,6320,14,2025-01-31,10385,545,0.002215
26,중원구,하대원동,19218,9678,9540,16916,8496,8420,3932,1877,2055,8075,34,2025-01-31,16916,76,0.004211
27,중원구,도촌동,26053,12637,13416,21648,10316,11332,4423,1953,2470,10768,50,2025-01-31,21648,-1016,0.004643
28,분당구,분당동,24504,12078,12426,20616,10067,10549,4122,1886,2236,10058,89,2025-01-31,20616,-482,0.008849
29,분당구,수내1동,17844,8488,9356,14727,6890,7837,2532,1032,1500,7848,129,2025-01-31,14727,-947,0.016437
30,분당구,수내2동,10452,5099,5353,7618,3692,3926,1229,554,675,3204,40,2025-01-31,7618,-234,0.012484
31,분당구,수내3동,13284,6583,6701,10444,5153,5291,1471,651,820,5125,29,2025-01-31,10444,-138,0.005659
32,분당구,정자동,13984,7117,6867,11998,6101,5897,2267,1068,1199,6300,61,2025-01-31,11998,204,0.009683
33,분당구,정자1동,30179,14301,15878,25492,11960,13532,4252,1977,2275,13976,277,2025-01-31,25492,-1572,0.019820
34,분당구,정자2동,14294,6800,7494,12587,5889,6698,2780,1087,1693,7274,60,2025-01-31,12587,-809,0.008249
35,분당구,정자3동,16695,7985,8710,13730,6495,7235,2434,1058,1376,6612,71,2025-01-31,13730,-740,0.010738
36,분당구,서현1동,30895,14990,15905,25372,12153,13219,4337,1963,2374,12668,168,2025-01-31,25372,-1066,0.013262
37,분당구,서현2동,17438,8610,8828,14526,7079,7447,2672,1233,1439,6555,61,2025-01-31,14526,-368,0.009306
38,분당구,이매1동,24817,12134,12683,20404,9843,10561,3799,1755,2044,9051,90,2025-01-31,20404,-718,0.009944
39,분당구,이매2동,13041,6393,6648,10669,5156,5513,2395,1166,1229,4415,57,2025-01-31,10669,-357,0.012911
40,분당구,야탑1동,16618,8190,8428,14540,7121,7419,3257,1519,1738,7545,60,2025-01-31,14540,-298,0.007952
41,분당구,야탑2동,15708,7444,8264,13213,6210,7003,3408,1571,1837,6005,81,2025-01-31,13213,-793,0.013489
42,분당구,야탑3동,26240,12900,13340,23164,11343,11821,5182,2289,2893,12512,60,2025-01-31,23164,-478,0.004795
43,분당구,금곡동,26873,12679,14194,23420,10896,12524,5525,2395,3130,12014,162,2025-01-31,23420,-1628,0.013484
44,분당구,구미동,28189,13365,14824,24604,11577,13027,5851,2566,3285,12530,158,2025-01-31,24604,-1450,0.012610
45,분당구,구미1동,16178,7795,8383,13949,6670,7279,2687,1223,1464,7013,88,2025-01-31,13949,-609,0.012548
46,분당구,판교동,26558,13036,13522,20372,9842,10530,2954,1419,1535,9021,96,2025-01-31,20372,-688,0.010642
47,분당구,삼평동,23773,11534,12239,19174,9210,9964,3013,1359,1654,9099,57,2025-01-31,19174,-754,0.006264
48,분당구,백현동,26416,12656,13760,22011,10373,11638,3879,1746,2133,10470,91,2025-01-31,22011,-1265,0.008691
49,분당구,운중동,37217,18185,19032,29477,14207,15270,4222,2052,2170,13564,172,2025-01-31,29477,-1063,0.012681

In [99]:
# Column 산술 연산을 통해 19세 이상 남녀 인구수 차이 구하기
data['19세 이상 남녀 차이'] = data['19세 이상_남'] - data['19세 이상_여']
data

,구별,동,인구수_계,인구수_남,인구수_여,19세 이상_계,19세 이상_남,19세 이상_여,65세 이상_계,65세 이상_남자,65세 이상_여자,세대수,재외국민,데이터기준일자,19세 이상 인구수,19세 이상 남녀 차이,재외국민/세대수
0,수정구,신흥1동,12278,6558,5720,11490,6145,5345,2934,1279,1655,7587,17,2025-01-31,11490,800,0.002241
1,수정구,신흥2동,31480,15265,16215,26514,12784,13730,4840,2222,2618,12269,42,2025-01-31,26514,-946,0.003423
2,수정구,신흥3동,10762,5757,5005,10035,5387,4648,2458,1133,1325,6457,9,2025-01-31,10035,739,0.001394
3,수정구,태평1동,13872,7195,6677,13061,6786,6275,3413,1510,1903,8332,21,2025-01-31,13061,511,0.002520
4,수정구,태평2동,13978,7064,6914,12821,6485,6336,3215,1377,1838,7645,18,2025-01-31,12821,149,0.002354
5,수정구,태평3동,11968,6153,5815,10996,5665,5331,2915,1311,1604,6511,17,2025-01-31,10996,334,0.002611
6,수정구,태평4동,11213,5782,5431,10168,5234,4934,2517,1120,1397,6024,12,2025-01-31,10168,300,0.001992
7,수정구,수진1동,11091,5875,5216,10464,5550,4914,3061,1363,1698,6781,12,2025-01-31,10464,636,0.001770
8,수정구,수진2동,14565,7357,7208,13379,6749,6630,3763,1706,2057,7520,33,2025-01-31,13379,119,0.004388
9,수정구,단대동,14349,7059,7290,12673,6176,6497,3091,1320,1771,6503,22,2025-01-31,12673,-321,0.003383
10,수정구,산성동,4543,2276,2267,4037,2005,2032,1093,471,622,2168,25,2025-01-31,4037,-27,0.011531
11,수정구,양지동,9050,4463,4587,8120,3985,4135,2060,900,1160,4245,6,2025-01-31,8120,-150,0.001413
12,수정구,복정동,10156,5735,4421,9431,5367,4064,1277,613,664,6562,18,2025-01-31,9431,1303,0.002743
13,수정구,위례동,45783,22143,23640,37007,17768,19239,6716,3115,3601,18842,119,2025-01-31,37007,-1471,0.006316
14,수정구,신촌동,4498,2379,2119,3677,1969,1708,571,269,302,2008,13,2025-01-31,3677,261,0.006474
15,수정구,고등동,11716,5735,5981,9822,4794,5028,1704,775,929,5259,28,2025-01-31,9822,-234,0.005324
16,수정구,시흥동,3419,1816,1603,3180,1690,1490,693,335,358,2058,17,2025-01-31,3180,200,0.008260
17,중원구,성남동,32221,16854,15367,29747,15615,14132,6769,3096,3673,18506,50,2025-01-31,29747,1483,0.002702
18,중원구,중앙동,16733,8516,8217,14295,7272,7023,3103,1409,1694,7580,18,2025-01-31,14295,249,0.002375
19,중원구,금광1동,19571,9592,9979,16276,7956,8320,2689,1220,1469,8225,16,2025-01-31,16276,-364,0.001945
20,중원구,금광2동,24116,11918,12198,21742,10724,11018,5184,2322,2862,12153,42,2025-01-31,21742,-294,0.003456
21,중원구,은행1동,9390,4641,4749,8332,4079,4253,1811,794,1017,4387,7,2025-01-31,8332,-174,0.001596
22,중원구,은행2동,21405,10557,10848,19530,9590,9940,5068,2167,2901,10791,48,2025-01-31,19530,-350,0.004448
23,중원구,상대원1동,23730,12374,11356,21365,11166,10199,5141,2343,2798,12139,23,2025-01-31,21365,967,0.001895
24,중원구,상대원2동,3042,1602,1440,2776,1457,1319,698,339,359,1607,10,2025-01-31,2776,138,0.006223
25,중원구,상대원3동,11311,5934,5377,10385,5465,4920,2816,1322,1494,6320,14,2025-01-31,10385,545,0.002215
26,중원구,하대원동,19218,9678,9540,16916,8496,8420,3932,1877,2055,8075,34,2025-01-31,16916,76,0.004211
27,중원구,도촌동,26053,12637,13416,21648,10316,11332,4423,1953,2470,10768,50,2025-01-31,21648,-1016,0.004643
28,분당구,분당동,24504,12078,12426,20616,10067,10549,4122,1886,2236,10058,89,2025-01-31,20616,-482,0.008849
29,분당구,수내1동,17844,8488,9356,14727,6890,7837,2532,1032,1500,7848,129,2025-01-31,14727,-947,0.016437
30,분당구,수내2동,10452,5099,5353,7618,3692,3926,1229,554,675,3204,40,2025-01-31,7618,-234,0.012484
31,분당구,수내3동,13284,6583,6701,10444,5153,5291,1471,651,820,5125,29,2025-01-31,10444,-138,0.005659
32,분당구,정자동,13984,7117,6867,11998,6101,5897,2267,1068,1199,6300,61,2025-01-31,11998,204,0.009683
33,분당구,정자1동,30179,14301,15878,25492,11960,13532,4252,1977,2275,13976,277,2025-01-31,25492,-1572,0.019820
34,분당구,정자2동,14294,6800,7494,12587,5889,6698,2780,1087,1693,7274,60,2025-01-31,12587,-809,0.008249
35,분당구,정자3동,16695,7985,8710,13730,6495,7235,2434,1058,1376,6612,71,2025-01-31,13730,-740,0.010738
36,분당구,서현1동,30895,14990,15905,25372,12153,13219,4337,1963,2374,12668,168,2025-01-31,25372,-1066,0.013262
37,분당구,서현2동,17438,8610,8828,14526,7079,7447,2672,1233,1439,6555,61,2025-01-31,14526,-368,0.009306
38,분당구,이매1동,24817,12134,12683,20404,9843,10561,3799,1755,2044,9051,90,2025-01-31,20404,-718,0.009944
39,분당구,이매2동,13041,6393,6648,10669,5156,5513,2395,1166,1229,4415,57,2025-01-31,10669,-357,0.012911
40,분당구,야탑1동,16618,8190,8428,14540,7121,7419,3257,1519,1738,7545,60,2025-01-31,14540,-298,0.007952
41,분당구,야탑2동,15708,7444,8264,13213,6210,7003,3408,1571,1837,6005,81,2025-01-31,13213,-793,0.013489
42,분당구,야탑3동,26240,12900,13340,23164,11343,11821,5182,2289,2893,12512,60,2025-01-31,23164,-478,0.004795
43,분당구,금곡동,26873,12679,14194,23420,10896,12524,5525,2395,3130,12014,162,2025-01-31,23420,-1628,0.013484
44,분당구,구미동,28189,13365,14824,24604,11577,13027,5851,2566,3285,12530,158,2025-01-31,24604,-1450,0.012610
45,분당구,구미1동,16178,7795,8383,13949,6670,7279,2687,1223,1464,7013,88,2025-01-31,13949,-609,0.012548
46,분당구,판교동,26558,13036,13522,20372,9842,10530,2954,1419,1535,9021,96,2025-01-31,20372,-688,0.010642
47,분당구,삼평동,23773,11534,12239,19174,9210,9964,3013,1359,1654,9099,57,2025-01-31,19174,-754,0.006264
48,분당구,백현동,26416,12656,13760,22011,10373,11638,3879,1746,2133,10470,91,2025-01-31,22011,-1265,0.008691
49,분당구,운중동,37217,18185,19032,29477,14207,15270,4222,2052,2170,13564,172,2025-01-31,29477,-1063,0.012681

In [95]:
# Column 산술 연산을 통해 재외국민과 세대수 비율 구하기
data['재외국민/세대수'] = data['재외국민'] / data['세대수']
data

,구별,동,인구수_계,인구수_남,인구수_여,19세 이상_계,19세 이상_남,19세 이상_여,65세 이상_계,65세 이상_남자,65세 이상_여자,세대수,재외국민,데이터기준일자,19세 이상 인구수,19세 이상 남녀 차이,재외국민/세대수
0,수정구,신흥1동,12278,6558,5720,11490,6145,5345,2934,1279,1655,7587,17,2025-01-31,11490,800,0.002241
1,수정구,신흥2동,31480,15265,16215,26514,12784,13730,4840,2222,2618,12269,42,2025-01-31,26514,-946,0.003423
2,수정구,신흥3동,10762,5757,5005,10035,5387,4648,2458,1133,1325,6457,9,2025-01-31,10035,739,0.001394
3,수정구,태평1동,13872,7195,6677,13061,6786,6275,3413,1510,1903,8332,21,2025-01-31,13061,511,0.002520
4,수정구,태평2동,13978,7064,6914,12821,6485,6336,3215,1377,1838,7645,18,2025-01-31,12821,149,0.002354
5,수정구,태평3동,11968,6153,5815,10996,5665,5331,2915,1311,1604,6511,17,2025-01-31,10996,334,0.002611
6,수정구,태평4동,11213,5782,5431,10168,5234,4934,2517,1120,1397,6024,12,2025-01-31,10168,300,0.001992
7,수정구,수진1동,11091,5875,5216,10464,5550,4914,3061,1363,1698,6781,12,2025-01-31,10464,636,0.001770
8,수정구,수진2동,14565,7357,7208,13379,6749,6630,3763,1706,2057,7520,33,2025-01-31,13379,119,0.004388
9,수정구,단대동,14349,7059,7290,12673,6176,6497,3091,1320,1771,6503,22,2025-01-31,12673,-321,0.003383
10,수정구,산성동,4543,2276,2267,4037,2005,2032,1093,471,622,2168,25,2025-01-31,4037,-27,0.011531
11,수정구,양지동,9050,4463,4587,8120,3985,4135,2060,900,1160,4245,6,2025-01-31,8120,-150,0.001413
12,수정구,복정동,10156,5735,4421,9431,5367,4064,1277,613,664,6562,18,2025-01-31,9431,1303,0.002743
13,수정구,위례동,45783,22143,23640,37007,17768,19239,6716,3115,3601,18842,119,2025-01-31,37007,-1471,0.006316
14,수정구,신촌동,4498,2379,2119,3677,1969,1708,571,269,302,2008,13,2025-01-31,3677,261,0.006474
15,수정구,고등동,11716,5735,5981,9822,4794,5028,1704,775,929,5259,28,2025-01-31,9822,-234,0.005324
16,수정구,시흥동,3419,1816,1603,3180,1690,1490,693,335,358,2058,17,2025-01-31,3180,200,0.008260
17,중원구,성남동,32221,16854,15367,29747,15615,14132,6769,3096,3673,18506,50,2025-01-31,29747,1483,0.002702
18,중원구,중앙동,16733,8516,8217,14295,7272,7023,3103,1409,1694,7580,18,2025-01-31,14295,249,0.002375
19,중원구,금광1동,19571,9592,9979,16276,7956,8320,2689,1220,1469,8225,16,2025-01-31,16276,-364,0.001945
20,중원구,금광2동,24116,11918,12198,21742,10724,11018,5184,2322,2862,12153,42,2025-01-31,21742,-294,0.003456
21,중원구,은행1동,9390,4641,4749,8332,4079,4253,1811,794,1017,4387,7,2025-01-31,8332,-174,0.001596
22,중원구,은행2동,21405,10557,10848,19530,9590,9940,5068,2167,2901,10791,48,2025-01-31,19530,-350,0.004448
23,중원구,상대원1동,23730,12374,11356,21365,11166,10199,5141,2343,2798,12139,23,2025-01-31,21365,967,0.001895
24,중원구,상대원2동,3042,1602,1440,2776,1457,1319,698,339,359,1607,10,2025-01-31,2776,138,0.006223
25,중원구,상대원3동,11311,5934,5377,10385,5465,4920,2816,1322,1494,6320,14,2025-01-31,10385,545,0.002215
26,중원구,하대원동,19218,9678,9540,16916,8496,8420,3932,1877,2055,8075,34,2025-01-31,16916,76,0.004211
27,중원구,도촌동,26053,12637,13416,21648,10316,11332,4423,1953,2470,10768,50,2025-01-31,21648,-1016,0.004643
28,분당구,분당동,24504,12078,12426,20616,10067,10549,4122,1886,2236,10058,89,2025-01-31,20616,-482,0.008849
29,분당구,수내1동,17844,8488,9356,14727,6890,7837,2532,1032,1500,7848,129,2025-01-31,14727,-947,0.016437
30,분당구,수내2동,10452,5099,5353,7618,3692,3926,1229,554,675,3204,40,2025-01-31,7618,-234,0.012484
31,분당구,수내3동,13284,6583,6701,10444,5153,5291,1471,651,820,5125,29,2025-01-31,10444,-138,0.005659
32,분당구,정자동,13984,7117,6867,11998,6101,5897,2267,1068,1199,6300,61,2025-01-31,11998,204,0.009683
33,분당구,정자1동,30179,14301,15878,25492,11960,13532,4252,1977,2275,13976,277,2025-01-31,25492,-1572,0.019820
34,분당구,정자2동,14294,6800,7494,12587,5889,6698,2780,1087,1693,7274,60,2025-01-31,12587,-809,0.008249
35,분당구,정자3동,16695,7985,8710,13730,6495,7235,2434,1058,1376,6612,71,2025-01-31,13730,-740,0.010738
36,분당구,서현1동,30895,14990,15905,25372,12153,13219,4337,1963,2374,12668,168,2025-01-31,25372,-1066,0.013262
37,분당구,서현2동,17438,8610,8828,14526,7079,7447,2672,1233,1439,6555,61,2025-01-31,14526,-368,0.009306
38,분당구,이매1동,24817,12134,12683,20404,9843,10561,3799,1755,2044,9051,90,2025-01-31,20404,-718,0.009944
39,분당구,이매2동,13041,6393,6648,10669,5156,5513,2395,1166,1229,4415,57,2025-01-31,10669,-357,0.012911
40,분당구,야탑1동,16618,8190,8428,14540,7121,7419,3257,1519,1738,7545,60,2025-01-31,14540,-298,0.007952
41,분당구,야탑2동,15708,7444,8264,13213,6210,7003,3408,1571,1837,6005,81,2025-01-31,13213,-793,0.013489
42,분당구,야탑3동,26240,12900,13340,23164,11343,11821,5182,2289,2893,12512,60,2025-01-31,23164,-478,0.004795
43,분당구,금곡동,26873,12679,14194,23420,10896,12524,5525,2395,3130,12014,162,2025-01-31,23420,-1628,0.013484
44,분당구,구미동,28189,13365,14824,24604,11577,13027,5851,2566,3285,12530,158,2025-01-31,24604,-1450,0.012610
45,분당구,구미1동,16178,7795,8383,13949,6670,7279,2687,1223,1464,7013,88,2025-01-31,13949,-609,0.012548
46,분당구,판교동,26558,13036,13522,20372,9842,10530,2954,1419,1535,9021,96,2025-01-31,20372,-688,0.010642
47,분당구,삼평동,23773,11534,12239,19174,9210,9964,3013,1359,1654,9099,57,2025-01-31,19174,-754,0.006264
48,분당구,백현동,26416,12656,13760,22011,10373,11638,3879,1746,2133,10470,91,2025-01-31,22011,-1265,0.008691
49,분당구,운중동,37217,18185,19032,29477,14207,15270,4222,2052,2170,13564,172,2025-01-31,29477,-1063,0.012681